### gets blogs entries
GET http://localhost:3003/api/blogs

### create blog entrie
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvcnJpIiwiaWQiOiI2Njg4NTRiZjk4M2U4Y2M4ZDAzMjVlNTQiLCJpYXQiOjE3MjEyMzU0NDh9.8aC1aeT4aGsYRQjUXAO_okGoiCRw439aQ6sh7Rz4GBc

{
  "title": "one blog for userExtractor test",
  "url": "http://github.com/barbarred",
  "likes": 34
}

### delete a blog entrie
DELETE http://localhost:3003/api/blogs/6697fec3682dd9624b38ea06
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvcnJpIiwiaWQiOiI2Njg4NTRiZjk4M2U4Y2M4ZDAzMjVlNTQiLCJpYXQiOjE3MjEyMzU0NDh9.8aC1aeT4aGsYRQjUXAO_okGoiCRw439aQ6sh7Rz4GBc

### update a entrie blog
PUT http://localhost:3003/api/blogs/66746c2fe27810bd54ca089c
Content-Type: application/json

{
  "title": "one entrie without like key",
  "author": "rorri",
  "url": "https://github.com/barbarred",
  "likes": 44
}